ACCOUNT_NAMES = [
    "ACM ENVIRONMENTAL PLC",
    "ACUMEN WASTE SERVICES",
    "707 LTD - CLICK WASTE",
    "AQUA FORCE SPECIAL WASTE LTD",
    "AMA WASTE",
    "ASSOCIATED WASTE MANAGEMENT LTD",
    "ASPREY ST JOHN & CO LTD",
    "ASH WASTE SERVICES LTD",
    "ACMS WASTE LIMITED",
    "A1 CHEMICAL WASTE MANAGEMENT LTD",
    "ALCHEMY METALS LTD",
    "BAKERS WASTE SERVICES LTD",
    "BIFFA WASTE SERVICES LIMITED",
    "BW SKIP HIRE",
    "BYWATERS (LEYTON) LIMITED",
    "BAGNALL & MORRIS WASTE SERVICES LTD",
    "BAILEYS SKIP HIRE AND RECYCLING LTD",
    "BUSINESS WASTE LTD",
    "BROWN RECYCLING LTD",
    "BKP WASTE & RECYCLING LTD",
    "BELFORD BROS SKIP HIRE LTD",
    "COUNTRYSTYLE RECYCLING LTD",
    "CARTWRIGHTS WASTE DISPOSAL SERVICES",
    "C & M WASTE MANAGEMENT LTD",
    "CHANGE WASTE RECYCLING LIMITED",
    "CHLOROS ENVIRONMENTAL LTD",
    "CHC WASTE FM LTD",
    "CLEANSING SERVICE GROUP LTD",
    "CIRCLE WASTE LTD",
    "CITY WASTE LONDON LTD",
    "CHESHIRE WASTE SKIP HIRE LIMITED",
    "CIRCOM LTD",
    "CITB",
    "DP SKIP HIRE LTD",
    "FORWARD ENVIRONMENTAL LTD",
    "EMN PLANT LTD",
    "E-CYCLE LIMITED",
    "ENVA ENGLAND LTD",
    "ELLGIA LTD",
    "ECO-CYCLE WASTE MANAGEMENT LTD",
    "ENVA WEEE RECYCLING SCOTLAND LTD",
    "FPWM LTD T/A FOOTPRINT RECYCLING",
    "FORWARD WASTE MANAGEMENT LTD",
    "FRESH START WASTE LTD",
    "FORVIS MAZARS LLP",
    "GREENZONE FACILITIES MANAGEMENT LTD",
    "GREENWAY ENVIRONMENTAL LTD",
    "GPT WASTE MANAGEMENT LTD",
    "GO GREEN",
    "GERMSTAR UK LTD",
    "GD ENVIRONMENTAL SERVICES LTD",
    "GREAT WESTERN RECYCLING LTD",
    "GRUNDON WASTE MANAGEMENT LTD",
    "GILLETT ENVIRONMENTAL LTD",
    "GO FOR IT TRADING LTD",
    "GO 4 GREENER WASTE MANAGEMENT LTD",
    "INTELLIGENT WASTE MANAGEMENT LIMITED",
    "J & B RECYCLING LTD",
    "JUST CLEAR LTD.",
    "JUST A STEP UK LTD",
    "J DICKINSON & SONS (HORWICH) LIMITED",
    "KENNY WASTE MANAGEMENT LTD",
    "KANE MANAGEMENT CONSULTANCY LTD",
    "LSS WASTE MANAGEMENT",
    "LTL SYSTEMS LTD",
    "MITIE WASTE & ENVIRONMENTAL SERVICES LIMITED",
    "M J CHURCH RECYCLING LTD",
    "M & M SKIP HIRE LTD",
    "MVV ENVIRONMENT",
    "MICK GEORGE RECYCLING LTD",
    "NWH WASTE SERVICES",
    "NATIONWIDE WASTE SERVICES LIMITED",
    "OPTIMA HEALTH UK LTD",
    "PREMIER WASTE RECYCLING LTD",
    "PEARCE RECYCLING COMPANY LTD",
    "PHOENIX ENVIRONMENTAL MANAGEMENT LTD",
    "PAPILO LTD",
    "RFMW UK LTD",
    "RIVERDALE PAPER PLC",
    "REMONDIS LTD",
    "ROYDON RESOURCE RECOVERY LIMITED",
    "RISINXTREME LIMITED",
    "RECORRA LTD",
    "SACKERS LTD",
    "SUEZ RECYCLING AND RECOVERY UK LTD",
    "SAFETY KLEEN UK LIMITED",
    "MOBIUS ENVIRONMENTAL LTD",
    "SUSTAINABLE WASTE SERVICES",
    "SELECT A SKIP UK LTD",
    "SLICKER RECYCLING LTD",
    "SOMMERS WASTE SOLUTIONS LIMITED",
    "SAICA NATUR UK LTD",
    "SITE CLEAR SOLUTIONS LTD",
    "SHARP BROTHERS (SKIPS) LTD",
    "SLM WASTE MANAGEMENT LIMITED",
    "SHREDALL (EAST MIDLANDS) LIMITED",
    "SCOTT WASTE LIMITED",
    "SMITHS (GLOUCESTER) LTD.",
    "TRADEBE NORTH WEST LTD",
    "THE WASTE BROKERAGE CO LTD",
    "T.WARD & SON LTD",
    "TERRACYCLE UK LIMITED",
    "UK WASTE SOLUTIONS LTD",
    "UBT (EU) LTD",
    "VEOLIA ES (UK) LTD",
    "VERTO RECYCLE LTD",
    "WASTE MANAGEMENT FACILITIES LTD",
    "RECONOMY (UK) LTD",
    "WATERMAN WASTE MANAGEMENT LTD",
    "WASTENOT LTD",
    "WASTE WISE MANAGEMENT SOLUTIONS",
    "WEEE (SCOTLAND) LTD",
    "WM101 LTD",
    "WHITKIRK WASTE SOLUTIONS LTD",
    "WILLIAMS ENVIRONMENTAL MANAGEMENT LTD",
    "WASTESOLVE LIMITED",
    "WMR WASTE SOLUTIONS LTD",
    "WHEELDON BROTHERS WASTE LTD",
    "WASTE CLOUD LIMITED",
    "YORWASTE LTD",
    "YES WASTE LIMITED",
]

# Registered office addresses sourced from Companies House
ADDRESS_OVERRIDES = {
    # A
    "ACM ENVIRONMENTAL PLC": "Kelsall House, Stafford Court, Stafford Park 1\nTelford, Shropshire\nTF3 3BD",
    "ACUMEN WASTE SERVICES": "Acumen House, Headlands Lane\nKnottingley, West Yorkshire\nWF11 0LA",
    "707 LTD - CLICK WASTE": "Kelsall House, Stafford Court, Stafford Park 1\nTelford, Shropshire\nTF3 3BD",
    "AQUA FORCE SPECIAL WASTE LTD": "Sprint Industrial Estate, Station Road\nFour Ashes, Wolverhampton\nWV10 7DB",
    "AMA WASTE": "Kelsall House, Stafford Court, Stafford Park 1\nTelford, Shropshire\nTF3 3BD",
    "ASSOCIATED WASTE MANAGEMENT LTD": "St Bernard's Mill, Gelderd Road\nGildersome, Morley, Leeds\nLS27 7NA",
    "ASPREY ST JOHN & CO LTD": "Suite 32, Hardmans Business Centre\nNew Hall Hey Road, Rawtenstall\nLancashire, BB4 6HH",
    "ASH WASTE SERVICES LTD": "The Mill, Morton\nOswestry, Shropshire\nSY10 8BH",
    "ACMS WASTE LIMITED": "Unit 23, Aston Fields Trade Park\nSugarbrook Road, Bromsgrove\nB60 3DW",
    "A1 CHEMICAL WASTE MANAGEMENT LTD": "Suite 6a, 10 Duke Street\nLiverpool\nL1 5AS",
    "ALCHEMY METALS LTD": "Cavendish Point, Cavendish Road\nStevenage, Hertfordshire\nSG1 2EU",
    # B
    "BAKERS WASTE SERVICES LTD": "70 Boston Road\nLeicester\nLE4 1AW",
    "BIFFA WASTE SERVICES LIMITED": "Biffa House, Rigby Court\nWokingham, Berkshire\nRG41 5BN",
    "BW SKIP HIRE": "263 Whitehall Road\nLeeds\nLS12 6ER",
    "BYWATERS (LEYTON) LIMITED": "Lea Riverside, Twelvetrees Crescent\nBow, London\nE3 3JG",
    "BAGNALL & MORRIS WASTE SERVICES LTD": "Iris House, Dock Road South\nBromborough, Wirral\nCH62 4SQ",
    "BAILEYS SKIP HIRE AND RECYCLING LTD": "4 Heritage Way\nCorby, Northants\nNN17 5XW",
    "BUSINESS WASTE LTD": "Artemis House, Eboracum Way\nHeworth Green, York\nYO31 7RE",
    "BROWN RECYCLING LTD": "Vanguard House, Sneyd Hill\nBurslem, Stoke-On-Trent\nST6 2DZ",
    "BKP WASTE & RECYCLING LTD": "Casbrook Park, Bunny Lane\nTimsbury, Romsey, Hampshire\nSO51 0PG",
    "BELFORD BROS SKIP HIRE LTD": "Mitre House, Pitt Street West\nBurslem, Stoke-On-Trent\nST6 3JW",
    # C
    "COUNTRYSTYLE RECYCLING LTD": "Ridham Dock, Ridham Dock Road\nIwade, Sittingbourne, Kent\nME9 8SR",
    "CARTWRIGHTS WASTE DISPOSAL SERVICES": "C/O Djh Chester City, 24 Castle Street\nChester\nCH1 2DS",
    "C & M WASTE MANAGEMENT LTD": "Kelsall House, Stafford Court, Stafford Park 1\nTelford, Shropshire\nTF3 3BD",
    "CHANGE WASTE RECYCLING LIMITED": "36 Newhaven Road\nEdinburgh\nEH6 5PY",
    "CHLOROS ENVIRONMENTAL LTD": "C/O Bkp Ltd, Casbrook Park, Bunny Lane\nTimsbury, Romsey\nSO51 0PG",
    "CHC WASTE FM LTD": "Pendre House, Pendre Industrial Estate\nTywyn, Gwynedd\nLL36 9LW",
    "CLEANSING SERVICE GROUP LTD": "Fusion 3, 1200 Parkway\nWhiteley, Fareham\nPO15 7AD",
    "CIRCLE WASTE LTD": "Kelsall House, Stafford Court, Stafford Park 1\nTelford, Shropshire\nTF3 3BD",
    "CITY WASTE LONDON LTD": "130 Shaftesbury Avenue, 2nd Floor\nLondon\nW1D 5EU",
    "CHESHIRE WASTE SKIP HIRE LIMITED": "Liverpool Road\nBackford, Chester, Cheshire\nCH1 6PE",
    "CIRCOM LTD": "Unit 2, Blackburn Road\nCoventry\nCV6 6LQ",
    "CITB": "Sand Martin House, Bittern Way\nPeterborough\nPE2 8TY",
    # D
    "DP SKIP HIRE LTD": "Ebenezer House, Ryecroft\nNewcastle-Under-Lyme, Staffordshire\nST5 2BE",
    # E
    "FORWARD ENVIRONMENTAL LTD": "White Rose Recycling Centre, Off Station Road\nSheffield, South Yorkshire\nS20 3PJ",
    "EMN PLANT LTD": "Sella Ness, Graven\nShetland\nZE2 9UP",
    "E-CYCLE LIMITED": "Unit 4, Dinas Isaf Industrial Estate\nWilliamstown, Tonypandy\nCF40 1NY",
    "ENVA ENGLAND LTD": "Enviro Building, Private Road No 4\nColwick Industrial Estate, Colwick, Nottingham\nNG4 2JT",
    "ELLGIA LTD": "Unit 7, Lancaster Way Business Park\nEly, Cambridgeshire\nCB6 3NW",
    "ECO-CYCLE WASTE MANAGEMENT LTD": "22-26 King Street\nKing's Lynn, Norfolk\nPE30 1HJ",
    "ENVA WEEE RECYCLING SCOTLAND LTD": "49 Burnbrae Road\nLinwood, Paisley, Renfrewshire\nPA3 3BD",
    # F
    "FPWM LTD T/A FOOTPRINT RECYCLING": "Meal Hill House, Sheffield Road\nJackson Bridge, Holmfirth, West Yorkshire\nHD9 7HS",
    "FORWARD WASTE MANAGEMENT LTD": "Forward House, East Moors Road\nCardiff\nCF24 5EE",
    "FRESH START WASTE LTD": "27 Beechfield Gardens\nRomford\nRM7 0EJ",
    "FORVIS MAZARS LLP": "30 Old Bailey\nLondon\nEC4M 7AU",
    # G
    "GREENZONE FACILITIES MANAGEMENT LTD": "The Corner House, Brunel Drive\nNewark, Nottinghamshire\nNG24 2EG",
    "GREENWAY ENVIRONMENTAL LTD": "Casbrook Park, Bunny Lane\nTimsbury, Romsey\nSO51 0PG",
    "GPT WASTE MANAGEMENT LTD": "57 King Street\nKnutsford\nWA16 6DX",
    "GO GREEN": "323 Bawtry Road\nDoncaster\nDN4 7PB",
    "GERMSTAR UK LTD": "St Mary's House, Netherhampton\nSalisbury, Wiltshire\nSP2 8PU",
    "GD ENVIRONMENTAL SERVICES LTD": "4a Brecon Court, William Brown Close\nLlantarnam Industrial Park, Cwmbran\nNP44 3AB",
    "GREAT WESTERN RECYCLING LTD": "Great Western Recycling, Avon Mill Lane\nKeynsham, Bristol\nBS31 2UG",
    "GRUNDON WASTE MANAGEMENT LTD": "Thames House, Oxford Road\nBenson, Wallingford, Oxfordshire\nOX10 6LX",
    "GILLETT ENVIRONMENTAL LTD": "Shorrock House, 1 Faraday Court\nFullwood, Preston, Lancashire\nPR2 9NB",
    "GO FOR IT TRADING LTD": "18 Camden Road\nTunbridge Wells, Kent\nTN1 2PT",
    "GO 4 GREENER WASTE MANAGEMENT LTD": "201 Slack Lane\nDerby\nDE22 3EE",
    # I
    "INTELLIGENT WASTE MANAGEMENT LIMITED": "Fiscal House, 367 London Road\nCamberley, Surrey\nGU15 3HQ",
    # J
    "J & B RECYCLING LTD": "3 Sidings Court, White Rose Way\nDoncaster\nDN4 5NU",
    "JUST CLEAR LTD.": "Ec1 Business Exchange, 80-83 Long Lane\nLondon\nEC1A 9ET",
    "JUST A STEP UK LTD": "4 Allen Birt Walk\nRugeley, Staffordshire\nWS15 2NG",
    "J DICKINSON & SONS (HORWICH) LIMITED": "Unit 5 Rivington View\nHorwich, Bolton\nBL6 5BN",
    # K
    "KENNY WASTE MANAGEMENT LTD": "Worsley Trading Estate, Lester Road\nLittle Hulton, Manchester\nM38 0PT",
    "KANE MANAGEMENT CONSULTANCY LTD": "Waldie House, C/O Barclay & Co C.A., Mill Road Industrial Estate\nLinlithgow, West Lothian\nEH49 7SF",
    # L
    "LSS WASTE MANAGEMENT": "Recycling House, Knowsthorpe Lane\nCross Green Industrial Park, Leeds\nLS9 0PF",
    "LTL SYSTEMS LTD": "Unit 3c Poplar Court, Atley Way\nNorth Nelson Industrial Estate, Cramlington, Northumberland\nNE23 1WR",
    # M
    "MITIE WASTE & ENVIRONMENTAL SERVICES LIMITED": "1 Bartholomew Lane\nLondon\nEC2N 2AX",
    "M J CHURCH RECYCLING LTD": "Star Farm, Marshfield\nChippenham\nSN14 8LH",
    "M & M SKIP HIRE LTD": "9 Worton Park, Cassington\nWitney, Oxfordshire\nOX29 4SX",
    "MVV ENVIRONMENT": "40 Creek Road\nPlymouth\nPL5 1FL",
    "MICK GEORGE RECYCLING LTD": "Second Floor, Arena Court, Crown Lane\nMaidenhead, Berkshire\nSL6 8QZ",
    # N
    "NWH WASTE SERVICES": "Unit 5 Mayfield Industrial Estate\nMayfield, Dalkeith, Midlothian\nEH22 4AD",
    "NATIONWIDE WASTE SERVICES LIMITED": "The Mill, Morton\nOswestry, Shropshire\nSY10 8BH",
    # O
    "OPTIMA HEALTH UK LTD": "Meadow Court, 2 Hayland Street\nSheffield\nS9 1BY",
    # P
    "PREMIER WASTE RECYCLING LTD": "H W Martin Group, Fordbridge Lane\nBlackwell, Alfreton, Derbyshire\nDE55 5JY",
    "PEARCE RECYCLING COMPANY LTD": "Pearce House, Acrewood Way\nSt Albans, Hertfordshire\nAL4 0JY",
    "PHOENIX ENVIRONMENTAL MANAGEMENT LTD": "Culverts Farm, Culverts Lane\nBoreham, Chelmsford, Essex\nCM3 3EW",
    "PAPILO LTD": "Suite 33, Lowry Mill, Lees Street\nSwinton, Manchester\nM27 6DB",
    # R
    "RFMW UK LTD": "Marlin Building, 4 Sadler Road\nLincoln, Lincolnshire\nLN6 3RS",
    "RIVERDALE PAPER PLC": "Earlsway, Team Valley Trading Estate\nGateshead, Tyne And Wear\nNE11 0RQ",
    "REMONDIS LTD": "Stephenson Way, Barrington Industrial Estate\nBedlington, Northumberland\nNE22 7DL",
    "ROYDON RESOURCE RECOVERY LIMITED": "Units 1-3, Junction Eco Park, Rake Lane\nSwinton, Manchester\nM27 8LU",
    "RISINXTREME LIMITED": "Oakmere, Belmont Business Park\nDurham\nDH1 1TW",
    "RECORRA LTD": "52 Lant Street\nLondon\nSE1 1RB",
    "RECONOMY (UK) LTD": "Kelsall House, Stafford Court, Stafford Park 1\nTelford, Shropshire\nTF3 3BD",
    # S
    "SACKERS LTD": "Railway Sidings, Gipping Road\nGreat Blakenham, Ipswich, Suffolk\nIP6 0JB",
    "SUEZ RECYCLING AND RECOVERY UK LTD": "2100 Coventry Road\nSheldon, Birmingham\nB26 3EA",
    "SAFETY KLEEN UK LIMITED": "Profile West, 950 Great West Road\nBrentford, Middlesex\nTW8 9ES",
    "MOBIUS ENVIRONMENTAL LTD": "Unit 8, Minster Court, Tuscam Way\nCamberley, Surrey\nGU15 3YY",
    "SUSTAINABLE WASTE SERVICES": "Ashcombe Court, Woolsack Way\nGodalming, Surrey\nGU7 1LQ",
    "SELECT A SKIP UK LTD": "Network House, Badgers Way\nOxon Business Park, Shrewsbury\nSY3 5AB",
    "SLICKER RECYCLING LTD": "Lombard House, Worcester Road\nStourport-On-Severn, Worcestershire\nDY13 9BZ",
    "SOMMERS WASTE SOLUTIONS LIMITED": "Suite B1, Park Centre, 210 Butterfield\nLuton, Bedfordshire\nLU2 8DL",
    "SAICA NATUR UK LTD": "144 Manchester Road\nCarrington, Manchester\nM31 4QN",
    "SITE CLEAR SOLUTIONS LTD": "12-13 Conduit Road\nNorton Canes, Cannock, Staffordshire\nWS11 9TJ",
    "SHARP BROTHERS (SKIPS) LTD": "Unit 6, Albright Industrial Estate, Ferry Lane\nRainham\nRM13 9BU",
    "SLM WASTE MANAGEMENT LIMITED": "Henwood House, Henwood\nAshford, Kent\nTN24 8DH",
    "SHREDALL (EAST MIDLANDS) LIMITED": "Joy House, Bestwood Business Park, Park Road\nBestwood Village, Nottingham\nNG6 8TQ",
    "SCOTT WASTE LIMITED": "Unit 9-10, Village Farm Road\nVillage Farm Industrial Estate, Pyle, Bridgend\nCF33 6BL",
    "SMITHS (GLOUCESTER) LTD.": "Brook Farm, Moreton Valence\nGloucester\nGL2 7ND",
    # T
    "TRADEBE NORTH WEST LTD": "Atlas House, Third Avenue\nGlobe Park, Marlow, Buckinghamshire\nSL7 1EY",
    "THE WASTE BROKERAGE CO LTD": "41 Mere View Industrial Estate\nYaxley, Peterborough\nPE7 3HS",
    "T.WARD & SON LTD": "James Freel Close, Furness Business Park\nBarrow In Furness, Cumbria\nLA14 2NW",
    "TERRACYCLE UK LIMITED": "Herschel House, 58 Herschel Street\nSlough, Berkshire\nSL1 1HD",
    # U
    "UK WASTE SOLUTIONS LTD": "Kelsall House, Stafford Court, Stafford Park 1\nTelford, Shropshire\nTF3 3BD",
    "UBT (EU) LTD": "The Precinct, Poseidon Way\nWarwick, Warwickshire\nCV34 6BY",
    # V
    "VEOLIA ES (UK) LTD": "Veolia House, 154A Pentonville Road\nLondon\nN1 9JE",
    "VERTO RECYCLE LTD": "Unit 197, Avenue B\nThorp Arch, Wetherby\nLS23 7BJ",
    # W
    "WASTE MANAGEMENT FACILITIES LTD": "4 Stratfield Saye, 20-22 Wellington Road\nBournemouth, Dorset\nBH8 8JN",
    "WATERMAN WASTE MANAGEMENT LTD": "70 Brunswick Street\nStockton-On-Tees, Cleveland\nTS18 1DW",
    "WASTENOT LTD": "100 Rutland Road\nSheffield\nS3 9PJ",
    "WASTE WISE MANAGEMENT SOLUTIONS": "Wastewise House, 46 Holland Street\nSutton Coldfield, West Midlands\nB72 1RR",
    "WEEE (SCOTLAND) LTD": "249 Govan Road\nGlasgow\nG51 1HJ",
    "WM101 LTD": "Unit 6, Station Road\nBakewell\nDE45 1GE",
    "WHITKIRK WASTE SOLUTIONS LTD": "Windmill House Farm, Forest Road\nWarsop, Nottinghamshire\nNG20 0EP",
    "WILLIAMS ENVIRONMENTAL MANAGEMENT LTD": "Recovery House, Hainault Business Park\n15-17 Roebuck Road, Ilford, Essex\nIG6 3TU",
    "WASTESOLVE LIMITED": "8 Water End Barns\nEversholt, Milton Keynes\nMK17 9EA",
    "WMR WASTE SOLUTIONS LTD": "10 Goldsmith Way, Eliot Business Park\nNuneaton, Warwickshire\nCV10 7RJ",
    "WHEELDON BROTHERS WASTE LTD": "Bridge House, Yeargate Industrial Estate\nBury New Road, Bury, Lancashire\nBL9 7HT",
    "WASTE CLOUD LIMITED": "30/2 Eskbank Office Complex\nHardengreen Industrial Estate, Dalkeith\nEH22 3NX",
    # Y
    "YORWASTE LTD": "Mount View, Standard Way\nNorthallerton, North Yorkshire\nDL6 2YD",
    "YES WASTE LIMITED": "Dipford House, Queens Square\nHuddersfield Road, Honley, Holmfirth\nHD9 6QZ",
}

BROKERS = {name: ADDRESS_OVERRIDES.get(name, "") for name in ACCOUNT_NAMES}
BROKER_LIST_TEXT = ", ".join(BROKERS.keys())
